//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVIDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ivimessageboardEntities : DbContext
    {
        public ivimessageboardEntities()
            : base("name=ivimessageboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblUserSecurity> tblUserSecurities { get; set; }
        public DbSet<tblError> tblErrors { get; set; }
        public DbSet<tblpostreply> tblpostreplies { get; set; }
        public DbSet<tblpostuploadedfile> tblpostuploadedfiles { get; set; }
        public DbSet<tblcategory> tblcategories { get; set; }
        public DbSet<tblpost> tblposts { get; set; }
    }
}
