//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVIDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpost
    {
        public int idposts { get; set; }
        public string posttitle { get; set; }
        public string postdescription { get; set; }
        public string postauthor { get; set; }
        public System.DateTime postdate { get; set; }
        public Nullable<int> postreplies { get; set; }
        public Nullable<int> postcategoryid { get; set; }
        public string postfileuploaded { get; set; }
    }
}
