//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVIDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpostreply
    {
        public int idpostreply { get; set; }
        public string postreplydescription { get; set; }
        public string postreplyauthor { get; set; }
        public int idreplyparent { get; set; }
        public string postreplydate { get; set; }
    }
}
