//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVIDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSecurity
    {
        public int UserSecurityId { get; set; }
        public string UserEmail { get; set; }
        public string UserSecurityQuestion { get; set; }
        public string UserSecurityAnswer { get; set; }
    }
}
